---
#
# Playbook to install the ELK stack + Beats on MacOS
#
- name: Install Elastic Stack components on MacOS
  hosts: localhost

  vars:
    version: "{{ tag }}"
    repo_base_url: https://artifacts.elastic.co/downloads
    base_install_dir: '{{ lookup("env", "ES_BASE_HOME") }}'
    run_option: "{{ run_option }}"


  tasks:
    # Install
    - { include_role: { name: install }, vars: { product: elasticsearch, product_family: elk,   target_os: },                 when: run_option == "install" }
    - { include_role: { name: install }, vars: { product: logstash,      product_family: elk,   target_os: },                 when: run_option == "install" }
    - { include_role: { name: install }, vars: { product: kibana,        product_family: elk,   target_os:  darwin-x86_64 },  when: run_option == "install" }
    - { include_role: { name: install }, vars: { product: apm-server,    product_family: elk,   target_os:  darwin-x86_64 },  when: run_option == "install" }
    - { include_role: { name: install }, vars: { product: metricbeat,    product_family: beats, target_os:  darwin-x86_64 },  when: run_option == "install" }
    - { include_role: { name: install }, vars: { product: filebeat,      product_family: beats, target_os:  darwin-x86_64 },  when: run_option == "install" }
    - { include_role: { name: install }, vars: { product: packetbeat,    product_family: beats, target_os:  darwin-x86_64 },  when: run_option == "install" }

    # Remove
    - { include_role: { name: remove },  vars: { product: elasticsearch, product_family: elk,   target_os: },                 when: run_option == "remove" }
    - { include_role: { name: remove },  vars: { product: logstash,      product_family: elk,   target_os: },                 when: run_option == "remove" }
    - { include_role: { name: remove },  vars: { product: kibana,        product_family: elk,   target_os:  darwin-x86_64 },  when: run_option == "remove" }
    - { include_role: { name: remove },  vars: { product: apm-server,    product_family: elk,   target_os:  darwin-x86_64 },  when: run_option == "remove" }
    - { include_role: { name: remove },  vars: { product: metricbeat,    product_family: beats, target_os:  darwin-x86_64 },  when: run_option == "remove" }
    - { include_role: { name: remove },  vars: { product: filebeat,      product_family: beats, target_os:  darwin-x86_64 },  when: run_option == "remove" }
    - { include_role: { name: remove },  vars: { product: packetbeat,    product_family: beats, target_os:  darwin-x86_64 },  when: run_option == "remove" }


  # tasks:
  #   - include_role:
  #         name: base_install
  #     vars:
  #       product: elasticsearch
  #       product_family: elk
  #       target_os:
  #     when: run_option == "install"
